# revision: 1-28-4
# revisionTags:
#   - default

# meshConfig:
#   discoverySelectors:
#     - matchLabels:
#         istio-discovery: enabled
global:
  configValidation: true
  hub: docker.io/istio
  istioNamespace: istio-system
  meshID: mesh1
  multiCluster:
    clusterName: cluster2
  network: network2
  proxy:
    privileged: true
